name:
  WinRMSharp CI

trigger:
  tags:
    include:
    - v*
        
jobs:
- template: azure-pipelines-template.yml
  parameters:
    os: windows
    architecture: x64
    frameworks: [netstandard2.0, netstandard2.1, net6.0, net7.0, net8.0, net9.0]
    publishBuild: true
